### ISSUE TITLE
neoterm.run() failing after toggling

### ISSUE THREAD

**Issue by bigjazzsound** [itmecho/neoterm.nvim#1]
Thanks for the awesome plugin.

I am running into an issue when I run `require("neoterm").run("terraform plan -out=tfplan")` and wait for my command to complete. Once it completes, I toggle the terminal to go back to nvim. Then when I execute `neoterm.run()` a second time, I get:

```
^Cterraform plan -out=tfplan

[Process exited 130]
```

**Comment by itmecho** [comment]
Hi, glad it's useful!

Hmm that's the output you get in the neoterm window? neoterm sends a `<C-c>` before running the command, I wonder if that's causing your shell to exit? Could you paste the output of `:set shell`?

**Comment by itmecho** [comment]
I've added a possible fix on master here: https://github.com/itmecho/neoterm.nvim/commit/f0528fc480647b85c6973b7abc5e6940551df9a7

Could you update and check if it's fixed your issue?

I also changed it so that it should run clear before the command you give it. This can be disabled either with the setup function or on individual calls by doing `run('ls', {clear = false})`

**Comment by bigjazzsound** [comment]
It works. Thank you!
