### ISSUE TITLE
Neoterm in vertical mode being off-screen in neovide GUI

### ISSUE THREAD

**Issue by LordMZTE** [itmecho/neoterm.nvim#3]
Using the neovide GUI for nvim, the neoterm terminal will appear off to the right side of the viewport when opening neoterm in vertical mode. Both horizontal and fullscreen mode work fine.

**Comment by itmecho** [comment]
Thanks for opening an issue! Would you be able to provide some more info? I can't reproduce it (`bspwm` on Arch Linux). In the screenshot you can see the border on the right hand side

![image](https://user-images.githubusercontent.com/8384983/168447539-41ed9b56-5fe1-4b81-af4b-0d54adba2af1.png)

**Comment by LordMZTE** [comment]
Sorry for not providing more info, I'll look into it tomorrow.

**Comment by LordMZTE** [comment]
So, I'm also on Arch but using i3 (don't think that matters tho). This is what neovide looks like opening neoterm:
![image](https://user-images.githubusercontent.com/28735087/168479793-eeac81d9-e941-4264-a243-e7c2d20d5dc6.png)
As you can see, it's not visible. The way I know its on the right is because my cursor has an animation, so I can see it moving.

My nvim config is available [here](https://mzte.de/git/LordMZTE/dotfiles/src/branch/master/.config/nvim).

**Comment by itmecho** [comment]
Hmm, are you using `neovide-bin` by chance? What version are you running?

**Comment by LordMZTE** [comment]
I'm actually using `neovide-git`, commit `g69902a4`.

**Comment by itmecho** [comment]
I've tried building `neovide` from source at that commit (`69902a4272d3095115cc68368206b4fd785a7b50`) and I still can't reproduce the behaviour you're getting. Have you tried building it from source manually? 

i.e.

```
git clone https://github.com/neovide/neovide
cd neovide
cargo build --release
```

Then run it again and see if it still happens?

**Comment by muemmel** [comment]
Cheers. I'm experiencing the same issue with neovide using the release binary. However, I think I know why that's happening. It seems as if neovide is placing the windows anchor on the left instead of right. Vertical mode places the window exactly at the last column, meaning it's completely off the screen.

I sorta fixed the issue by changing the target column to about half the value of ui.width.

But I wanted to somewhat customize the position and border of the window, so I added code for that. See my [commit here](https://github.com/itmecho/neoterm.nvim/commit/446acefe8286644abf3bea2413658c3cca4553f7).

I'd like to create a pull request, if that's ok with you @itmecho 

---
Edit
Forgot to add:
Tested my changes with vertical, horizontal and fullscreen mode without winopts and/or winhighlights without errors. Old configs don't seem to be affected by the changes.

**Comment by itmecho** [comment]
@muemmel thanks for digging into it!

Yea, open a pr for it, that'd be brilliant =]

**Comment by muemmel** [comment]
@itmecho Posted the pull request, if you find the time.

**Comment by dpi0** [comment]
@itmecho I also noticed this on `arch linux` (hyprland) with `neovide` from the official repos on `0.13.3-2`

Due to the deprecation of `mode` option this issue now occurs whenever the width is `1` or `100%` in any `position`

![image](https://github.com/user-attachments/assets/7e2c16cf-feca-4a13-80a5-2436d7209663)
